import sys
i = int(input("Enter a integer: "))
f = float(input("Enter a float: "))
c = complex(input("Enter a complex number: "))
b1 = bool(input("Enter 1st  boolean value: "))
b2 = bool(input("Enter 2nd boolean value: "))
s = input("Enter a string: ")
print()
print("PART 1:Variable Creation")
print(type(i))
print(type(f))
print(type(c))
print(type(b1))
print(type(s))
print()
print("PART 2:Memory size of Data")
print(sys.getsizeof(i))
print(sys.getsizeof(f))
print(sys.getsizeof(c))
print(sys.getsizeof(b1))
print(sys.getsizeof(s))
print()
print("PART 3:Exploring Complex numbers")
print("Real part of complex number: ", c.real)
print("Imaginary part of complex number: ", c.imag)
print("Magnitude of complex number: ", abs(c))
print()
print("PRT 4:Boolean operations")
print("AND operation: ", b1 and b2)
print("OR operation: ", b1 or b2)
print("NOT operation on 1st boolean value: ", not b1)
print("NOT operation on 2nd boolean value: ", not b2)
print()
print("PART 5:Type Conversion")
print("Integer to float: ", float(i))
print("Float to integer: ", int(f))
print("Integer to string: ",str(i))
if s.isdigit()==True:
    print("String to integer: ", int(s))
else :
    print("Cannot convert string to integer.")
print("Boolean to integer: ",int(b1))
print("Integer to complex: ", complex(i))
